cps extend timeout
MycroftAI/mycroft-core pull request #2666
Opened 2020-08-18 06:08 UTC by JarbasAl

adds ```CPS_extend_timeout``` util method to CommonPlaySkill 

usage
```python
 def CPS_match_query_phrase(self, phrase):  # , media_type
        # this skill takes long to return results
        self.CPS_extend_timeout(10)
```

2020-08-18 06:45 UTC, devops-mycroft commented
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2666))

2020-09-13 16:47 UTC, JarbasAl commented
closed this one by accident

2020-09-13 17:25 UTC, devops-mycroft commented
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2666))

2020-09-14 05:42 UTC, forslund requested changes
Glad it was by mistake! This looks like a nice and simple addition, and seems to work as intended.

Please add a docstring to the new method so it's populated in the readthedocs api documentation.

2020-09-20 21:13 UTC, devops-mycroft commented
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2666))

2020-09-20 22:36 UTC, devops-mycroft commented
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2666))

2020-09-24 06:50 UTC, devops-mycroft commented
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2666))

2020-11-14 01:04 UTC, krisgesling commented
Hey @forslund were you happy with this now? 

I think we'll want to add in something that can reject the request based on some criteria but that can be a follow up PR.
eg (intentionally absurd):
- Skill requests 3 hour extension
- Skill puts extension request in never ending loop
- total wait time has exceeded some threshold
- etc

2020-11-14 10:03 UTC, forslund commented
Yes, quite happy. I think the sanity check might be better to implement on the receiving end.

2020-11-14 10:03 UTC, forslund approved these changes

2020-11-15 01:22 UTC, merged

2020-11-15 02:44 UTC, JarbasAl commented
> I think we'll want to add in something that can reject the request based on some criteria but that can be a follow up PR.
> eg (intentionally absurd):
> 
>     * Skill requests 3 hour extension
> 
>     * Skill puts extension request in never ending loop
> 
>     * total wait time has exceeded some threshold
> 
>     * etc

PR ready for review ;)