Add basic test cases for gui interface
MycroftAI/mycroft-core pull request #2697
Opened 2020-09-17 20:37 UTC by forslund

## Description
Add test cases for the gui interface.

## How to test
Ensure the unittests pass

## Contributor license agreement signed?
CLA [ Yes ]

2020-09-17 21:37 UTC, devops-mycroft commented
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2697))

2020-09-17 22:24 UTC, devops-mycroft commented
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2697))

2020-09-17 22:30 UTC, krisgesling requested changes
These are awesome, thanks so much!

A couple of minor things, but they look great overall.

2020-09-17 22:30 UTC, krisgesling commented on test/unittests/enclosure/test_gui.py
> +        """Check that send even sends in the correct format."""
tiny typo: even > event

2020-09-17 22:30 UTC, krisgesling commented on test/unittests/enclosure/test_gui.py
> +        """Assure that a timeout response results in not connected."""
Assure > Ensure

2020-09-18 05:27 UTC, forslund commented on test/unittests/enclosure/test_gui.py
> +        self.assertEqual(sent_message.data['page'], [image_url])
Good suggestion. Should be updated now.

2020-09-18 05:28 UTC, forslund commented
Thanks for the quick review. I've pushed updates and the issues should be resolved.

2020-09-18 06:02 UTC, devops-mycroft commented
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2697))

2020-09-18 06:36 UTC, krisgesling approved these changes

2020-09-18 06:36 UTC, merged