Add pause and resume capability to TTS playback thread
MycroftAI/mycroft-core pull request #2940
Opened 2021-07-02 23:39 UTC by krisgesling

## Description
This adds pause and resume functionality to the TTS playback thread for use in barge in.

From Ken:

> Barge-In is not an issue for Precise, however, core has some issues. When a wave file is speaking the recognizer confuses the wav file for the mic. Ducking helps a bit with this but its more useful as an audible confirmation as the recognizer still favors this over the mic input. The proper solution is to pause the audio output until the recognizer has consumed the utterance.
> 
> The root problem arises from the tts module which does not use the audio service but it wants to act like one. It has start and stop method and a queue but no pause or resume. This PR corrects that. It also contains the code which uses this new functionality to help with the barge-in process.

Replication of #2939 against the dev branch so it doesn't get lost.

## How to test
Unit tests need to be added.

> Enable your barge-in config flag and use a long playing dialog skill like the new duck duck go or wiki skill (these return an abstract rather than a single sentence) and then say 'stop'. Without this PR this will not work 90% of the time.

## Contributor license agreement signed?
- [x] CLA

2021-07-03 00:20 UTC, devops-mycroft commented
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2940))

2021-07-03 15:42 UTC, forslund requested changes
I believe there is a possible lock scenario if the thread is stopped while in a pause waiting state (and also the speech client is shut down), unlikely but should is simple to put in safeguards against. See https://github.com/forslund/mycroft-core/commit/33a430e8746685823d2aa2d0a72e57294b465cd3 for a simple fix.

The other comments are mainly suggestions on improvements and can be ignored. If they are deemed useful you can cherry-pick them from [forslund/mycroft-core/tree/feature/tts-pause-resume](https://github.com/forslund/mycroft-core/tree/feature/tts-pause-resume)

2021-07-09 20:18 UTC, chrisveilleux commented on mycroft/audio/speech.py
> +    LOG.debug("Listen=%s, Speak:%s" % (listen, utterance))
I agree this should be kept as an info level log.  Knowing what the device thought it heard and what it said in response is quite useful.

2021-07-09 20:19 UTC, chrisveilleux commented on mycroft/tts/tts.py
> +                sleep(0.2)
I would go one step further.  Why use threading.Event() when we have an event-driven architecture with a message bus?  What is a good reason to use threading.Event() instead?

2021-07-10 06:53 UTC, forslund commented on mycroft/tts/tts.py
> +                sleep(0.2)
Do you mean terminate the playback thread and restart it on the message?

2024-09-08 08:10 UTC, forslund commented
Closing PR since we're archiving the repo

2024-09-08 08:10 UTC, closed without merging